In [46]:
import tensorflow as tf
import pandas as pd
from tensorflow.keras.datasets import boston_housing
from sklearn import preprocessing

In [47]:
(train_x,train_y),(test_x,test_y)=boston_housing.load_data()

In [53]:
df = boston_housing.load_data()
df

((array([[1.23247e+00, 0.00000e+00, 8.14000e+00, ..., 2.10000e+01,
          3.96900e+02, 1.87200e+01],
         [2.17700e-02, 8.25000e+01, 2.03000e+00, ..., 1.47000e+01,
          3.95380e+02, 3.11000e+00],
         [4.89822e+00, 0.00000e+00, 1.81000e+01, ..., 2.02000e+01,
          3.75520e+02, 3.26000e+00],
         ...,
         [3.46600e-02, 3.50000e+01, 6.06000e+00, ..., 1.69000e+01,
          3.62250e+02, 7.83000e+00],
         [2.14918e+00, 0.00000e+00, 1.95800e+01, ..., 1.47000e+01,
          2.61950e+02, 1.57900e+01],
         [1.43900e-02, 6.00000e+01, 2.93000e+00, ..., 1.56000e+01,
          3.76700e+02, 4.38000e+00]]),
  array([15.2, 42.3, 50. , 21.1, 17.7, 18.5, 11.3, 15.6, 15.6, 14.4, 12.1,
         17.9, 23.1, 19.9, 15.7,  8.8, 50. , 22.5, 24.1, 27.5, 10.9, 30.8,
         32.9, 24. , 18.5, 13.3, 22.9, 34.7, 16.6, 17.5, 22.3, 16.1, 14.9,
         23.1, 34.9, 25. , 13.9, 13.1, 20.4, 20. , 15.2, 24.7, 22.2, 16.7,
         12.7, 15.6, 18.4, 21. , 30.1, 15.1, 18.7,  9.6, 31.

In [6]:
print("train shape: ",train_x.shape)
print("test shape: ",test_x.shape)
print("actual train output:",train_y.shape)
print("actual test output:",test_y.shape)

train shape:  (404, 13)
test shape:  (102, 13)
actual train output: (404,)
actual test output: (102,)


In [7]:
train_x[0]

array([  1.23247,   0.     ,   8.14   ,   0.     ,   0.538  ,   6.142  ,
        91.7    ,   3.9769 ,   4.     , 307.     ,  21.     , 396.9    ,
        18.72   ])

In [8]:
train_y[0]

15.2

In [10]:
#normalization for preprocessing
train_x=preprocessing.normalize(train_x)
test_x=preprocessing.normalize(test_x)

In [11]:
train_x[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945359, 0.00778265, 0.00782786, 0.6007879 ,
       0.04109624, 0.77671895, 0.03663436])

In [ ]:
train_y[0]

In [39]:
from tensorflow.python import metrics
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import *
def HousePricePredictionModel():  
	model=Sequential()
	model.add(Dense(128,activation='relu',input_shape=(train_x[0].shape)))
	model.add(Dense(64,activation='relu'))
	model.add(Dense(32,activation='relu'))
	model.add(Dense(1))
	model.compile(optimizer='adam',loss='mse',metrics=['mae'])
	return model

In [40]:
import numpy as np
k=4
num_val_samples=len(train_x)
num_epochs=100
all_scores=[]

In [41]:
model= HousePricePredictionModel()
history=model.fit(x=train_x,y=train_y,epochs=num_epochs,batch_size=1,verbose=1,validation_data=(test_x,test_y))

Epoch 1/100
404/404 [==============================] - 2s 4ms/step - loss: 128.7931 - mae: 8.2821 - val_loss: 63.0394 - val_mae: 5.8322
Epoch 2/100
404/404 [==============================] - 1s 3ms/step - loss: 64.9954 - mae: 5.7676 - val_loss: 59.5293 - val_mae: 5.5749
Epoch 3/100
404/404 [==============================] - 1s 3ms/step - loss: 61.0366 - mae: 5.4910 - val_loss: 58.4192 - val_mae: 5.5012
Epoch 4/100
404/404 [==============================] - 1s 2ms/step - loss: 58.8063 - mae: 5.2789 - val_loss: 52.8515 - val_mae: 5.3864
Epoch 5/100
404/404 [==============================] - 1s 2ms/step - loss: 57.1081 - mae: 5.0925 - val_loss: 58.5803 - val_mae: 5.9920
Epoch 6/100
404/404 [==============================] - 1s 2ms/step - loss: 53.9273 - mae: 5.0644 - val_loss: 50.9698 - val_mae: 5.1563
Epoch 7/100
404/404 [==============================] - 1s 2ms/step - loss: 52.5596 - mae: 5.0056 - val_loss: 48.6688 - val_mae: 5.2145
Epoch 8/100
404/404 [==============================] -

In [45]:
mse, mae = model.evaluate(test_x, test_y)
print('Mean squared error on test data: ', mse)
print('Mean absolute error on test data: ', mae)

4/4 [==============================] - 0s 3ms/step - loss: 27.8984 - mae: 3.5095
Mean squared error on test data:  27.89837074279785
Mean absolute error on test data:  3.5094945430755615
